### ISSUE TITLE
How to replicate results

### ISSUE THREAD

**Issue by Lingxiao108105** [Frank-ZY-Dou/EMDM#3]
Thank you for your outstanding works.

May I know the exact command and configuration for each dataset? I want to reproduce the results in your paper.

Also, I want to know how many epochs of training are required for each dataset.

**Comment by Andy-Zhou2** [comment]
Hi,

Please refer to the instructions in the README. The configuration will be loaded automatically according to the dataset chosen. Please let us know if you think there is a bug, and we can provide further assistance.

We recommend training the model for as long as possible, especially for the T2M ones. For reference, we recommend >20000 epochs for humanact12, >3500 epochs for humanml3d, and >7000 epochs for kit.
