### ISSUE TITLE
Performance on HumanML3D dataset

### ISSUE THREAD

**Issue by Lingxiao108105** [Frank-ZY-Dou/EMDM#4]
Thanks for your wonderful work, but i have some problems to accurately reproduce the results on HumanML3D dataset.

I use the HumanML3D dataset and the pre-trained model provided in this repository. I use the provided command to evaluate 
"CUDA_VISIBLE_DEVICES=0 python eval_humanml.py --model_path ${model_path} --eval_mode wo_mm --dataset humanml". 
Then I cannot accurately reproduce the performance in the main paper's Table 1.

![image](https://github.com/user-attachments/assets/e3e8b656-969e-4e17-8e69-47b3287402b9)

For the data I use, I download HumanML3D dataset from GUESS. https://github.com/Xuehao-Gao/GUESS

I did not change anything in the code.

I wonder if someone also suffers from this problem and how to fix this problem.

**Comment by Andy-Zhou2** [comment]
Thank you for your question. Following MDM, we have used replication_times of 5 to save time during batch evaluation, which might have increased the variability of results. The numbers may also differ from machine to machine due to architectural differences and seeding.

**Comment by Frank-ZY-Dou** [comment]
> Thanks for your wonderful work, but i have some problems to accurately reproduce the results on HumanML3D dataset.
> 
> I use the HumanML3D dataset and the pre-trained model provided in this repository. I use the provided command to evaluate "CUDA_VISIBLE_DEVICES=0 python eval_humanml.py --model_path ${model_path} --eval_mode wo_mm --dataset humanml". Then I cannot accurately reproduce the performance in the main paper's Table 1.
> 
> ![image](https://private-user-images.githubusercontent.com/71265122/362536092-e3e8b656-969e-4e17-8e69-47b3287402b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MTE3NzgsIm5iZiI6MTcyNTgxMTQ3OCwicGF0aCI6Ii83MTI2NTEyMi8zNjI1MzYwOTItZTNlOGI2NTYtOTY5ZS00ZTE3LThlNjktNDdiMzI4NzQwMmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDE2MDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YzA4MGU4ZTVmZTZhZGMwZDU2NjFlMGFlNzllNTI3OTA1Mzc3YmMxZjJlOGQ0NWM3YmZjYzRjMWE4OWVjY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3FpE5LSS7JfIHRRfWyOr7mARIpP5gNdnTLsdt4QLIrw)
> 
> For the data I use, I download HumanML3D dataset from GUESS. https://github.com/Xuehao-Gao/GUESS
> 
> I did not change anything in the code.
> 
> I wonder if someone also suffers from this problem and how to fix this problem.

Feel free to reach out via WeChat if you need any assistance :)

Best,
Frank

**Comment by Lingxiao108105** [comment]
> > Thanks for your wonderful work, but i have some problems to accurately reproduce the results on HumanML3D dataset.
> > I use the HumanML3D dataset and the pre-trained model provided in this repository. I use the provided command to evaluate "CUDA_VISIBLE_DEVICES=0 python eval_humanml.py --model_path ${model_path} --eval_mode wo_mm --dataset humanml". Then I cannot accurately reproduce the performance in the main paper's Table 1.
> > ![image](https://private-user-images.githubusercontent.com/71265122/362536092-e3e8b656-969e-4e17-8e69-47b3287402b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MTE3NzgsIm5iZiI6MTcyNTgxMTQ3OCwicGF0aCI6Ii83MTI2NTEyMi8zNjI1MzYwOTItZTNlOGI2NTYtOTY5ZS00ZTE3LThlNjktNDdiMzI4NzQwMmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDE2MDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YzA4MGU4ZTVmZTZhZGMwZDU2NjFlMGFlNzllNTI3OTA1Mzc3YmMxZjJlOGQ0NWM3YmZjYzRjMWE4OWVjY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3FpE5LSS7JfIHRRfWyOr7mARIpP5gNdnTLsdt4QLIrw)
> > For the data I use, I download HumanML3D dataset from GUESS. https://github.com/Xuehao-Gao/GUESS
> > I did not change anything in the code.
> > I wonder if someone also suffers from this problem and how to fix this problem.
> 
> Feel free to reach out via WeChat if you need any assistance :)
> 
> Best, Frank

That is very helpful. May I know how to reach out via WeChat?
My email is lingxiao108105@gmail.com

Best,
Lingxiao
