### ISSUE TITLE
What should I do if I want to train with multiple GPUs?

### ISSUE THREAD

**Issue by wjxxyz** [Frank-ZY-Dou/EMDM#5]
What should I do if I want to train with multiple GPUs?

**Comment by Frank-ZY-Dou** [comment]
Hi,

Thank you for your interest! At the moment, we don’t have plans to develop a multi-GPU version. However, if you’d like to train on multiple GPUs, you might explore these options:

DataParallel: A straightforward solution, though limited in scalability.
DistributedDataParallel (DDP): Recommended for improved performance and scalability.
Additionally, PyTorch Lightning could be a convenient alternative.

Best regards,
Frank

**Comment by wjxxyz** [comment]
> Hi, 你好
> 
> Thank you for your interest! At the moment, we don’t have plans to develop a multi-GPU version. However, if you’d like to train on multiple GPUs, you might explore these options:感谢您的关注！目前，我们没有开发多 GPU 版本的计划。但是，如果您想在多个 GPU 上进行训练，则可以探索以下选项：
> 
> DataParallel: A straightforward solution, though limited in scalability.DataParallel：一个简单的解决方案，但可扩展性有限。 DistributedDataParallel (DDP): Recommended for improved performance and scalability.DistributedDataParallel （DDP）：建议使用以提高性能和可伸缩性。 Additionally, PyTorch Lightning could be a convenient alternative.此外，PyTorch Lightning 可能是一个方便的替代方案。
> 
> Best regards, 此致敬意 Frank 弗兰克

In my model training, the training speed is quite slow. I'm using a 3090 GPU. May I ask what GPU are you using? Also, are there any methods to speed up the training?

**Comment by Frank-ZY-Dou** [comment]
> > Hi, 你好
> > Thank you for your interest! At the moment, we don’t have plans to develop a multi-GPU version. However, if you’d like to train on multiple GPUs, you might explore these options:感谢您的关注！目前，我们没有开发多 GPU 版本的计划。但是，如果您想在多个 GPU 上进行训练，则可以探索以下选项：
> > DataParallel: A straightforward solution, though limited in scalability.DataParallel：一个简单的解决方案，但可扩展性有限。 DistributedDataParallel (DDP): Recommended for improved performance and scalability.DistributedDataParallel （DDP）：建议使用以提高性能和可伸缩性。 Additionally, PyTorch Lightning could be a convenient alternative.此外，PyTorch Lightning 可能是一个方便的替代方案。
> > Best regards, 此致敬意 Frank 弗兰克
> 
> In my model training, the training speed is quite slow. I'm using a 3090 GPU. May I ask what GPU are you using? Also, are there any methods to speed up the training?

Hi, the training details are available in the final version of the ECCV24 Appendix for this paper. The training process is slow due to the complexity of modeling distributions across multiple denoising steps, which makes training challenging.

**Comment by wjxxyz** [comment]
> > > Hi, 你好
> > > Thank you for your interest! At the moment, we don’t have plans to develop a multi-GPU version. However, if you’d like to train on multiple GPUs, you might explore these options:感谢您的关注！目前，我们没有开发多 GPU 版本的计划。但是，如果您想在多个 GPU 上进行训练，则可以探索以下选项：
> > > DataParallel: A straightforward solution, though limited in scalability.DataParallel：一个简单的解决方案，但可扩展性有限。 DistributedDataParallel (DDP): Recommended for improved performance and scalability.DistributedDataParallel （DDP）：建议使用以提高性能和可伸缩性。 Additionally, PyTorch Lightning could be a convenient alternative.此外，PyTorch Lightning 可能是一个方便的替代方案。
> > > Best regards, 此致敬意 Frank 弗兰克
> > 
> > 
> > In my model training, the training speed is quite slow. I'm using a 3090 GPU. May I ask what GPU are you using? Also, are there any methods to speed up the training?
> 
> Hi, the training details are available in the final version of the ECCV24 Appendix for this paper. The training process is slow due to the complexity of modeling distributions across multiple denoising steps, which makes training challenging.

I noticed that you are using a 4090 GPU. May I ask how many days it took to train the entire model? Also, approximately how many epochs were needed to achieve similar results?

**Comment by wjxxyz** [comment]
I'm training each epoch in 100 seconds, and I'm wondering if it's due to my hardware.
