### ISSUE TITLE
FID Metric Error

### ISSUE THREAD

**Issue by lsy-92** [Frank-ZY-Dou/EMDM#6]
Thank you for your wonderful research.

I downloaded your model and tried to evaluate the performance by evaluation.

But is there a reason for this error in my dataset?

Thanks.

Traceback (most recent call last):
  File "/mnt/data/project/EMDM/eval_humanml.py", line 339, in <module>
    result = evaluate_humanml(args)
  File "/mnt/data/project/EMDM/eval_humanml.py", line 323, in evaluate_humanml
    return evaluation(eval_wrapper, gt_loader, eval_motion_loaders, log_file, replication_times, diversity_times, mm_num_times, run_mm=run_mm)
  File "/mnt/data/project/EMDM/eval_humanml.py", line 166, in evaluation
    fid_score_dict = evaluate_fid(eval_wrapper, gt_loader, acti_dict, f)
  File "/mnt/data/project/EMDM/eval_humanml.py", line 95, in evaluate_fid
    fid = calculate_frechet_distance(gt_mu, gt_cov, mu, cov)
  File "/mnt/data/project/EMDM/data_loaders/humanml/utils/metrics.py", line 148, in calculate_frechet_distance
    raise ValueError('Imaginary component {}'.format(m))
ValueError: Imaginary component 0.05246677499786136

**Comment by lsy-92** [comment]
And there is no VQVAE Train code.

**Comment by Frank-ZY-Dou** [comment]
Hello, and thank you so much for your interest in our work!  
As kindly noted in the README, we would appreciate it if you could follow MDM's instructions to set up the evaluation code and model. Please feel free to reach out if you have any questions!
<img width="877" alt="image" src="https://github.com/user-attachments/assets/0ac0ca12-9507-42bc-922d-62e735c8b366">

MDM⬇️
<img width="901" alt="image" src="https://github.com/user-attachments/assets/0634812d-c851-401d-9b84-3a8c55102d97">

Thanks!

**Comment by lsy-92** [comment]
Thank you for your answer.

I already follow MDM's Instructrions to set up the evaluation.

but it can't calculate FID Score only.

I got other evaluation metrics.

Here is a result.

The FID score was intentionally annotated because of an error.

==================== Replication 0 ====================
Time: 2024-12-06 17:40:05.360726
========== Evaluating Matching Score ==========
---> [ground truth] Matching Score: 2.9776
---> [ground truth] R_precision: (top 1): 0.5188 (top 2): 0.7112 (top 3): 0.8043 
---> [vald] Matching Score: 3.1570
---> [vald] R_precision: (top 1): 0.4775 (top 2): 0.6660 (top 3): 0.7646 
Model: ground truth, Embedding Size: (4640, 512)
Model: vald, Embedding Size: (1024, 512)
Time: 2024-12-06 17:40:07.760441
========== Evaluating Diversity ==========
Activation Shape: (4640, 512)
Activation NaN Count: 0
Activation Inf Count: 0
num_samples :  4640
---> [ground truth] Diversity: 9.4873
Activation Shape: (1024, 512)
Activation NaN Count: 0
Activation Inf Count: 0
num_samples :  1024
---> [vald] Diversity: 9.8371
Time: 2024-12-06 17:40:07.767244
========== Evaluating MultiModality ==========
---> [vald] Multimodality: 1.5244
!!! DONE !!!

I'd appreciate your advice.

Thanks.

**Comment by lsy-92** [comment]
It is numpy version problem.

I used numpy 2.2.0.

After I changed numpy 1.23.5, It is Okay.

Thanks.

**Comment by Frank-ZY-Dou** [comment]
Glad you fixed it! Kindly let us know if you encounter any problems.

Best,
Frank
