### ISSUE TITLE
I'm curious about latent dimension.

### ISSUE THREAD

**Issue by lsy-92** [Frank-ZY-Dou/EMDM#7]
Thank you for your remarkable results.
I am curious about why you chose to set the latent dimension to 1024.
In the MDM model you based your work on, I understand that the latent dimension is set to 512.
I tried reducing the latent dimension to 256 using your model, but the performance was significantly degraded.
I’m curious to know why the latent dimension must be set to 1024 and why you didn’t attempt to reduce this size further.
Thank you.

**Comment by Frank-ZY-Dou** [comment]
Hi Thanks for your interest!
We empirically found that appropriately increasing the latent space is important for model performance, especially when using fewer denoising steps. One possible explanation is that an increase in model capacity is necessary to ensure good performance even with fewer denoising steps, achieving a balance between speed and maintaining generation quality.
